// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMKayxxwV33qg06ClwUXbc2IIAxt1KsEg',
    appId: '1:15724884705:web:792f6148ce7126e3a4fda0',
    messagingSenderId: '15724884705',
    projectId: 'tbc-remind-app',
    authDomain: 'tbc-remind-app.firebaseapp.com',
    databaseURL: 'https://tbc-remind-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tbc-remind-app.appspot.com',
    measurementId: 'G-645D6LRG11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkp2SXSNMJf2QbwcSvPxTGcBRkcY6BHjM',
    appId: '1:15724884705:android:aae350604dd0d7c5a4fda0',
    messagingSenderId: '15724884705',
    projectId: 'tbc-remind-app',
    databaseURL: 'https://tbc-remind-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tbc-remind-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAinZvy7b_f_B9jyJWyXvLl2MuWHH73MRY',
    appId: '1:15724884705:ios:70f245b16d55d4d5a4fda0',
    messagingSenderId: '15724884705',
    projectId: 'tbc-remind-app',
    databaseURL: 'https://tbc-remind-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tbc-remind-app.appspot.com',
    iosClientId: '15724884705-vj9b3nni4gjb69il8nb863o5ff5tbt7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAinZvy7b_f_B9jyJWyXvLl2MuWHH73MRY',
    appId: '1:15724884705:ios:70f245b16d55d4d5a4fda0',
    messagingSenderId: '15724884705',
    projectId: 'tbc-remind-app',
    databaseURL: 'https://tbc-remind-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tbc-remind-app.appspot.com',
    iosClientId: '15724884705-vj9b3nni4gjb69il8nb863o5ff5tbt7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbcApp',
  );
}
